language: ruby
cache: bundler
rvm:
  - 2.3.1
  - 2.2.5
env:
  - GSM_TEST_MODE: CI
  - CODECLIMATE_REPO_TOKEN: a3b92a7e935316eab6293228fa587784c95b9dd10ab61adb4fdb9ecb6ca330d8
after_sucess:
  - bundle exec codeclimate-test-reporter
notifications:
  email: false
  slack: navyblue-team:ioO5diAGc5WUQVDKc5BH1UbE